
    // 1 - Intrdução a Variáveis
    String variavelNome = "Wellington Santos"
    print(variavelNome);
    int valorVariavel = 10;
    print(valorVariavel);
    bool ehVerdadeiro = true
    List<String> ListaDePalavras = ["Wellington","Desenvolvedor"];
    print('listaDePalavras');

    // 2 - introdução null-safety

    String? nome;
    nome = 'ABC'
    print(nome!);
    nome = null;

    late String sobrenome;
    sobrenome = 'William';
    print(sobrenome);
    sobrenome = null;
    // 3 - IF e SWITCH
    // 4 - Metodos e Classes
    // 5 - Future, Async e Await
    // 6 - Orientação a objetos 
    // 7 - Herança, Polimorfismo e Abstração
}